### ISSUE TITLE
opening attachments

### ISSUE THREAD

**Issue by rhaynes74** [tzok/taskattach#1]
Is there an easy way to open files that have been attached in this way?

**Comment by tzok** [comment]
Hi @rhaynes74. As you can see, this repository was updated 9 years ago for the last time. I no longer use TaskWarrior and I cannot guarantee that taskattach will still work.

Having said that, the syntax for opening attachments is to run `taskattach.sh NUMBER` and the program will list all available attachments. You can then select one of them to be opened.
